const express = require('express')
const router = express.Router()

const routesConquistas = require('./routesConquistas')
const routesGenero = require('./routesGenero')
const routesJogo = require('./routesJogo')
const routesJogoGenero = require('./routesJogoGenero')
const routesJogoPlataforma = require('./routesJogoPlataforma')
const routesPaises = require('./routesPaises')
const routesPlataforma = require('./routesPlataforma')
const routesPreco = require('./routesPreco')
const routesSexo = require('./routesSexo')
const routesTipoPagamento = require('./routesTipoPagamento')
const routesDlc = require('./routesDlc')

router.use('/conquistas', routesConquistas)
router.use('/genero', routesGenero)
router.use('/jogo', routesJogo)
router.use('/jogo-genero', routesJogoGenero)
router.use('/jogo-plataforma', routesJogoPlataforma)
router.use('/paises', routesPaises)
router.use('/plataforma', routesPlataforma)
router.use('/preco', routesPreco)
router.use('/sexo', routesSexo)
router.use('/tipo-pagamento', routesTipoPagamento)
router.use('/dlc', routesDlc)

module.exports = router