const express = require('express')
const router = express.Router()

const routesConquistas = require('./routesConquistas')
const routesGenero = require('./routesGenero')
const routesJogo = require('./routesJogo')
const routesJogoGenero = require('./routesJogoGenero')
const routesJogoPlataforma = require('./routesJogoPlataforma')
const routesPaises = require('./routesPaises')
const routesPlataforma = require('./routesPlataforma')
const routesPreco = require('./routesPreco')
const routesSexo = require('./routesSexo')
const routesTipoPagamento = require('./routesTipoPagamento')
const routesDlc = require('./routesDlc')
const routesUsuario = require('./routesUsuario')
const routesEmpresa = require('./routesEmpresa')
const routesPublicacaoJogoDaEmpresa = require('./routesPublicacaoJogoDaEmpresa')
const routesPublicacaoJogoDoUsuario = require('./routesPublicacaoJogoDoUsuario')
const routesAvaliacao = require('./routesAvaliacao')

router.use('/conquistas', routesConquistas)
router.use('/genero', routesGenero)
router.use('/jogo', routesJogo)
router.use('/jogo-genero', routesJogoGenero)
router.use('/jogo-plataforma', routesJogoPlataforma)
router.use('/paises', routesPaises)
router.use('/plataforma', routesPlataforma)
router.use('/preco', routesPreco)
router.use('/sexo', routesSexo)
router.use('/tipo-pagamento', routesTipoPagamento)
router.use('/dlc', routesDlc)
router.use('/usuario', routesUsuario)
router.use('/empresa', routesEmpresa)
router.use('/publicacao-jogo-da-empresa', routesPublicacaoJogoDaEmpresa)
router.use('/publicacao-jogo-do-usuario', routesPublicacaoJogoDoUsuario)
router.use('/avaliacao', routesAvaliacao)

module.exports = router